on:
  schedule:
    - cron: "20 2 * * *"

jobs:
  delete-package-versions:
    name: Delete untagged package versions older than 8 weeks
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "gcc clang"
          tag-selection: untagged
          cut-off: 8w
          dry-run: false  # consider toggling this to true on your first run