on:
  workflow_dispatch:
  schedule:
    - cron: "32 * * * *"

jobs:
  delete-old-untagged:
    name: "Delete untagged containers older that 4 weeks"
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-selection: untagged
          cut-off: 4w
          dry-run: true
